### ISSUE TITLE
[Bug]: The `-q` option doesn't take effect for jpegxl

### ISSUE THREAD

**Issue by Kosette** [SalOne22/rimage#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`-q/--quality` doesn't make any difference when combined with `-f jpegxl`.

- OS: Debian 12 for WSL.

### Expected behavior

generating images of varying quality with `-q/--quality`

### Library Version

0.9.1 (latest)

**Comment by Mikachu2333** [comment]
The -q opinion is disabled on release v0.10.0 when you choose the jxl format.

**Comment by SalOne22** [comment]
The current implementation of the `-q` (quality) flag in rimage can be somewhat unclear, especially since some codecs, like jpegxl, do not support lossy compression. To address this, in the upcoming major release, I am planning to introduce a more versatile API. This new API will offer distinct options tailored to each codec, ensuring clearer and more effective control over the compression and quality settings for different image formats.

**Comment by SalOne22** [comment]
Resolved in #188
