### ISSUE TITLE
[Feature]: add decoder fn new(bytes: impl Into<Vec<u8>>)

### ISSUE THREAD

**Issue by vuhe** [SalOne22/rimage#212]
### Description

The decoder method should be consistent with zune, as I use the decoder to decode the&[u8] read from the compressed file, and the try_new method will cause unnecessary additional overhead.

I used translation software, please understand if my language is a bit strange.

**Comment by SalOne22** [comment]
Some of the decoders in zune-image use a `try_new` method because they rely on external crates for decoding. For example `jpeg-xl` decoder has this method https://docs.rs/zune-image/latest/zune_image/codecs/jpeg_xl/struct.JxlDecoder.html#impl-JxlDecoder%3CR%3E. These crates might not be fully compatible with zune-image's design. If you have a better way to handle this, we welcome your contributions!

**Comment by vuhe** [comment]
Thank you for your reply.

Or simply wrapper it with rimage trait, as I need to use a decoder selected based on the image type, I need to repeat the following code:

```rust
let mut decoder = AvifDecoder::try_new(reader).unwrap();
let img = <AvifDecoder<ZByteReader<Vec<u8>>> as DecoderTrait<Vec<u8>>>::decode(&mut decoder).unwrap();
```

I just want decode, but this seems too complicated. 
If you don't plan to design it to be fully compatible with zune-image, can you provide a more concise API?

There is no new method, so I cannot use macro_rules either.

**Comment by SalOne22** [comment]
Latest pre-release of `zune-image` has a `from_decoder` method that simplifies this.

After merge of #208, support for this release will be added. So decoding will be as easy as this:

```rs
let decoder = AvifDecoder::try_new(file)?;
return Image::from_decoder(decoder);
```

**Comment by vuhe** [comment]
This looks great, I will replace it after PR merge.

**Comment by SalOne22** [comment]
Update, support for latest pre-relase of `zune-image` is added in version `0.11.0-next.1`
